config/routes.rb
ActsAsAddressable::Engine.routes.draw do
  resources :locations

end

app/models/acts_as_addressable/location.rb
module ActsAsAddressable
  class Location < ActiveRecord::Base
    belongs_to :addressable, polymorphic: true

    validates_presence_of :city, :postal_code, :street_1
    validate :multiple_primary, if: "self.primary?"

    scope :primary, -> { where primary: true }

    def self.for_addressable(location)
      where(addressable_id: location.addressable_id).where(addressable_type: location.addressable_type)
    end

    def has_primary?
      !!primary_location_for_addressable
    end

    def primary_location_for_addressable
      @primary_location_for_addressable ||= Location.primary.for_addressable(self).first
    end

    private

    def multiple_primary
      if has_primary?
        unless self.id && self.id == primary_location_for_addressable.id
          errors.add(:base, 'A primary address already exists.')
        end
      end
    end

  end
end

app/controllers/acts_as_addressable/application_controller.rb
module ActsAsAddressable
  class ApplicationController < ActionController::Base
  end
end

app/controllers/acts_as_addressable/locations_controller.rb
require_dependency "acts_as_addressable/application_controller"

module ActsAsAddressable
  class LocationsController < ApplicationController
    before_action :set_location, only: [:show, :edit, :update, :destroy]

    # GET /locations
    def index
      @locations = Location.all
    end

    # GET /locations/1
    def show
    end

    # GET /locations/new
    def new
      @location = Location.new
    end

    # GET /locations/1/edit
    def edit
    end

    # POST /locations
    def create
      @location = Location.new(location_params)

      if @location.save
        redirect_to @location, notice: 'Location was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /locations/1
    def update
      if @location.update(location_params)
        redirect_to @location, notice: 'Location was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /locations/1
    def destroy
      @location.destroy
      redirect_to locations_url, notice: 'Location was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_location
        @location = Location.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def location_params
        params.require(:location).permit(:country_code, :street_1, :street_2, :city, :region, :postal_code, :latitude, :longitude, :addressable_id, :addressable_type, :mailing, :physical, :primary)
      end
  end
end

app/helpers/acts_as_addressable/application_helper.rb
module ActsAsAddressable
  module ApplicationHelper
  end
end

app/views/acts_as_addressable/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :country_code %><br>
    <%= f.text_field :country_code %>
  </div>
  <div class="field">
    <%= f.label :street_1 %><br>
    <%= f.text_field :street_1 %>
  </div>
  <div class="field">
    <%= f.label :street_2 %><br>
    <%= f.text_field :street_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :addressable_id %><br>
    <%= f.text_field :addressable_id %>
  </div>
  <div class="field">
    <%= f.label :mailing %><br>
    <%= f.text_field :mailing %>
  </div>
  <div class="field">
    <%= f.label :physical %><br>
    <%= f.check_box :physical %>
  </div>
  <div class="field">
    <%= f.label :primary %><br>
    <%= f.check_box :primary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts_as_addressable/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/acts_as_addressable/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Country code</th>
      <th>Street 1</th>
      <th>Street 2</th>
      <th>City</th>
      <th>Region</th>
      <th>Postal code</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Addressable</th>
      <th>Mailing</th>
      <th>Physical</th>
      <th>Primary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.country_code %></td>
        <td><%= location.street_1 %></td>
        <td><%= location.street_2 %></td>
        <td><%= location.city %></td>
        <td><%= location.region %></td>
        <td><%= location.postal_code %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.addressable %></td>
        <td><%= location.mailing %></td>
        <td><%= location.physical %></td>
        <td><%= location.primary %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/acts_as_addressable/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/acts_as_addressable/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country code:</strong>
  <%= @location.country_code %>
</p>

<p>
  <strong>Street 1:</strong>
  <%= @location.street_1 %>
</p>

<p>
  <strong>Street 2:</strong>
  <%= @location.street_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Region:</strong>
  <%= @location.region %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @location.postal_code %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Addressable:</strong>
  <%= @location.addressable %>
</p>

<p>
  <strong>Mailing:</strong>
  <%= @location.mailing %>
</p>

<p>
  <strong>Physical:</strong>
  <%= @location.physical %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @location.primary %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/layouts/acts_as_addressable/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActsAsAddressable</title>
  <%= stylesheet_link_tag    "acts_as_addressable/application", media: "all" %>
  <%= javascript_include_tag "acts_as_addressable/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>